### ISSUE TITLE
How to generate PBXProj Identifiers by python?

### ISSUE THREAD

**Issue by FormioCour** [samdmarshall/xcodeproj#1]
I found this blog https://pewpewthespells.com/blog/pbxproj_identifiers.html

How to implement TSGenerateUniqueGlobalID by python?
How to convert 12 byte identifier to 24 byte identifier ?

**Comment by samdmarshall** [comment]
https://github.com/samdmarshall/xcparse/blob/develop/xcparse/Helpers/xcrun_helper.py#L17-L47
